# Generated by Django 5.1.6 on 2025-05-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0006_adoptionrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptionrequest',
            old_name='god',
            new_name='dog',
        ),
    ]
