# Generated by Django 5.1.6 on 2025-05-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0007_rename_god_adoptionrequest_dog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='Status',
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
